[workspace]
authors = ["Menchen <huangmenchen@gmail.com>"]
channels = ["conda-forge"]
name = "pycameleon-gui"
platforms = ["osx-arm64","linux-64","linux-aarch64","win-64"]
version = "0.1.0"

[tasks]

[dependencies]
rerun-sdk = ">=0.27.2,<0.28"
numba = ">=0.62.1,<0.63"
python = ">=3.13.9,<3.14"
scipy = ">=1.16.3,<2"

[pypi-dependencies]
pycameleon = ">=0.2.0, <0.3"

[tasks.toucan_ndvi]
cmd = "python toucan_ndvi_rerun.py"
env_file = ".env"
